/* This file was generated by ./tinfo/MKfallback.sh */

/*
 * DO NOT EDIT THIS FILE BY HAND!
 */

#include <curses.priv.h>

NCURSES_EXPORT(const TERMTYPE *) _nc_fallback (const char *name GCC_UNUSED)
{
	/* the fallback list is empty */
    return((TERMTYPE *)0);
}
